/**!
 * Mikado.js v0.7.5 (Light)
 * Copyright 2019 Nextapps GmbH
 * Author: Thomas Wilkerling
 * Licence: Apache-2.0
 * https://github.com/nextapps-de/mikado
 */
(function(){'use strict';var q;var w={},z={},A={},B={},C={};function D(a,b,c){if(!(this instanceof D))return new D(a,b,c);a.nodeType||(c=b,b=a,a=null);a?this.mount(a):(this.b=this.f=null,this.length=0);this.init(b,c)}var E=D.register=function(a,b){b||(b=a,a=b.n);z[a]=b;return D};D.prototype.mount=function(a){if(this.b!==a){this.key&&this.b&&(this.b._o=this.l,this.l=a._o||{});this.b=a;F(this);var b;if(!(b=a._d)){b=a.children;for(var c=b.length,d=Array(c),f=0,e;f<c;f++)e=b[f],d[f]=e;b=a._d=d}this.f=b;this.length=this.f.length}return this};
D.prototype.index=function(a){for(var b=0,c=this.length;b<c;b++)if(this.f[b]===a)return b;return-1};D.prototype.node=function(a){return this.f[a]};
D.prototype.init=function(a,b){"string"===typeof a?a=z[a]:(b||!a||a.n||(b=a,a=null),a?a.n&&E(a):a=z[this.u]);b||(b=this.C||{});this.B=!1!==b.reuse;this.state=b.state||w;this.cache=!1!==b.cache;this.C=b;var c=a.n;this.u!==c&&(this.u=c,this.m=a.d,this.w=this.g=null,this.A=!1!==b.prefetch&&G(this,a),F(this),this.l=(this.key=a.k)&&{},a=b.pool,this.v=this.B&&!1!==a&&"key"!==a&&(B[c]||(B[c]=[])),this.o=this.key&&!1!==a&&"queue"!==a&&(C[c]||(C[c]={})),this.size=this.v&&b.size);return this};
D.once=function(a,b,c,d,f){var e=new D(a,b);"function"===typeof d&&(f=d,d=null);if(f){var g=f;f=function(){e.destroy(1);g()}}e.render(c,d,f);f||e.destroy(1);return D};function F(a){if(a.b){var b=a.b._t;b!==a.u&&(a.b._t=a.u,b&&(a.l={},a.remove(0,a.length)))}}q=D.prototype;
q.create=function(a,b,c){var d=this.key,f=d&&a[d],e,g;if(d&&(g=this.o)&&(e=g[f]))if(g){if(g[f]=null,g=this.v){var l=e._n;e._n=null;var h=g.pop();h!==e&&(h._n=l,g[l]=h)}}else d=0;else if((e=this.v)&&e.length)e=e.pop(),g&&(e._n=null,g[e._k]=null);else{var r=1;(e=this.A)&&this.cache&&(e.$={})}this.apply(e,a,b,c);r&&(e=this.A.cloneNode(!0),this.cache&&(e.$=this.A.$));d&&(e._k=f,this.l[f]=e);return e};
q.apply=function(a,b,c,d){this.A||(this.A=a=G(this,z[this.u]));if(!this.m)return this.w(a._p||H(this,a),a.$,b,d,c),this};
q.render=function(a,b){var c=this.length;if(!a&&this.m)return this.f[0]||this.add(),this;var d=a.length;if("undefined"===typeof d)a=[a],d=1;else if(!d)return this.remove(0,c);var f=(this.o||!this.B)&&this.key;f||this.B||(this.remove(0,c,d),c=0);var e=c<d?c:d,g=0;if(g<e)for(;g<e;g++){var l=this.f[g],h=a[g];if(f&&l._k!==h[f])return this.reconcile(a,b,g,1);this.update(l,h,b,g)}if(g<d)for(;g<d;g++)this.add(a[g],b);else d<c&&this.remove(d,c-d);return this};
q.reconcile=function(a,b,c,d){var f=this.f,e=this.l,g=a.length,l=f.length,h=l>g?l:g,r=0,x=this.key;for(c||(c=0);c<h;c++){var p=void 0;if(c<g){var n=a[c],k=c>=l,m=void 0,u=void 0,y=void 0;if(!k&&(m=f[c],u=n[x],y=m._k,y===u)){d&&this.update(m,n,b,c);continue}if(k||!e[u]){d&&(k||!this.o?(l++,h=l>g?l:g,this.add(n,b,c)):this.replace(m,n,b,c));continue}for(var v=k=void 0,t=c+1;t<h;t++)if(!k&&t<l&&f[t]._k===u&&(k=t+1),!v&&t<g&&a[t][x]===y&&(v=t+1),k&&v){k>=v?(p=f[k-1],this.b.insertBefore(p,m),d&&this.update(p,
n,b,c),k===v?(1<t-c&&this.b.insertBefore(m,f[k]),f[c]=f[t],f[t]=m):(I(f,k-1,c),r++)):(n=v-1+r,this.b.insertBefore(m,f[n]||null),I(f,c,(n>l?l:n)-1),r--,c--);p=1;break}}p||(this.remove(c),l--,h=l>g?l:g,c--)}return this};function I(a,b,c,d){var f=d||a[b];d&&b++;if(b<c)for(;b<c;b++)a[b]=a[b+1];else for(;b>c;b--)a[b]=a[b-1];a[c]=f}
q.add=function(a,b,c,d){if(!d)if("number"===typeof b){c=b;b=null;var f=1}else if(c||0===c)f=1;c=d||f?c:this.length;a=this.create(a,b,c);f?(this.b.insertBefore(a,this.f[c]),I(this.f,this.length-1,c,a),this.length++):(d?this.b.replaceChild(a,d):(this.b.appendChild(a),this.length++),this.f[c]=a);return this};q.clear=function(){this.length&&this.remove(0,this.length);return this};q.destroy=function(a){a&&this.unload();this.length=0;this.l=this.f=this.b=this.u=this.g=this.w=this.A=null};
q.append=function(a,b,c){if("number"===typeof b){c=b;b=null;var d=1}else d=c||0===c;for(var f=a.length,e=0;e<f;e++)this.add(a[e],b,d?c++:null);return this};
q.remove=function(a,b,c){var d=this.length;a&&("object"===typeof a?a=this.index(a):0>a&&(a=d+a-1));if(!d||a>=d)return this;b?0>b&&(a-=b+1,0>a&&(a=0),b*=-1):b=1;!a&&b>=d?(a=this.f,b=a.length,this.b.textContent="",this.b._d=this.f=c?Array(c):[],d=0):(a=this.f.splice(a,b),d-=b);this.length=d;if(this.v&&!this.o&&1<b){c=a;for(var f=c.length,e=f/2|0,g=0,l;g<e;g++)l=c[g],c[g]=c[f-g-1],c[f-g-1]=l}for(c=0;c<b;c++)f=a[c],d&&this.b.removeChild(f),J(this,f);return this};
function J(a,b){if(a.key){var c=b._k;a.l[c]=null;a.o&&(a.o[c]=b)}a.v&&(c=a.v.length,!a.size||c<a.size)&&(a.o&&(b._n=c),a.v[c]=b)}q.replace=function(a,b,c,d){"undefined"===typeof d&&("number"===typeof a?(d=a,a=this.f[d]):d=this.index(a));this.add(b,c,d,a);J(this,a);return this};q.update=function(a,b,c,d){"undefined"===typeof d&&("number"===typeof a?(d=a,a=this.f[a]):d=this.index(a));if(this.key){var f=a._k,e=b[this.key];f!==e&&(this.l[f]=null,this.l[e]=a,a._k=e)}return this.apply(a,b,c,d)};
function H(a,b){for(var c=a.g.length,d={},f=Array(c),e=0,g;e<c;e++){g=a.g[e];var l=e,h;if(!(h=d[g])){h=b;for(var r=0,x=g.length,p="";r<x;r++){var n=g[r];p+=n;d[p]?h=d[p]:(">"===n?h=h.firstElementChild:"+"===n?h=h.nextElementSibling:"|"===n&&(h=h.firstChild),d[p]=h)}}f[l]=h}return b._p=f}var K;
function G(a,b,c,d,f){if(!c){var e=A[b.n+(a.cache?"$":"")];if(e)return a.w=e.w,a.m=e.m,a.g=e.g,e.node}e=document.createElement(b.t||"div");c||(c=0,d="&",K="",a.g=[],e._p=f=[],a.cache&&(e.$={}));var g=b.s,l=b.i,h=b.x,r=b.h,x=b.a,p=b.c,n=b.j,k=a.g.length,m=0,u="";n&&(u+=";"+n,-1<u.indexOf("self")&&(m=2));p&&("object"===typeof p?(p=""+p[0],u+=a.cache?";v="+p+";if(s._c"+k+"!==v){s._c"+k+"=v;self.className=v}":p?";self.className="+p:"",m++):e.className=p);if(x){var y;x&&(y=Object.keys(x));for(p=0;p<y.length;p++){n=
y[p];var v=void 0;!x||(v=x[n]);"object"===typeof v?(v=""+v[0],u+=a.cache?";v="+v+";if(s['_a_"+n+k+"']!==v){s['_a_"+n+k+"']=v;self.setAttribute('"+n+"',v)}":v?";self.setAttribute('"+n+"',"+v+")":"",m++):e.setAttribute(n,v)}}g&&("string"===typeof g?e.style.cssText=g:g.length&&(g=g[0],u+=a.cache?";v="+g+";if(s._cs"+k+"!==v){s._cs"+k+"=v;(self._s||(self._s=self.style)).cssText=v}":g?";self.style.cssText="+g:"",m++));if(!l)if(h){if(g="object"===typeof h){var t=!1;h=""+h[0]}y=document.createTextNode(h);
g&&(m&&k++,a.g[k]=d+"|",f[k]=y,L(m,a.cache&&!t?";v="+h+";if(s._x"+k+"!==v){s._x"+k+"=v;self.nodeValue=v}":h?";self.nodeValue="+h:"",k),t&&(t=h,h=["_x",k],a.proxy||(a.proxy={}),(a.proxy[t]||(a.proxy[t]=[])).push(h)),m&&k--);e.appendChild(y)}else r&&("object"===typeof r?(r=""+r[0],u+=a.cache?";v="+r+";if(s._h"+k+"!==v){s._h"+k+"=v;self.innerHTML=v}":r?";self.innerHTML="+r:"",m++):e.innerHTML=r);m?(a.g[k]=d,f[k]=e,a.m=0,L(m,u,k)):u&&(K+=u);if(l)if(l.length)for(k=">",m=0;m<l.length;m++)m&&(k+="+"),u=
l[m],e.appendChild(G(a,u,c+m+1,d+k,f));else e.appendChild(G(a,l,c+1,d+">",f));c||(!a.m&&K&&(a.w=Function("p","s","data","index","view",'"use strict";var self,v'+K)),A[b.n+(a.cache?"$":"")]={w:a.w,m:a.m,g:a.g,node:e});return e}function L(a,b,c){K=1<a?K+(";self=p["+c+"]"+b):K+b.replace(/self/g,"p["+c+"]")}D.prototype.unload=function(a){a?"object"===typeof a&&(a=a.n):a=this.u;a&&(z[a]=null,B[a]=C[a]=A[a]=null,A[a+"$"]=null);return this};D.unregister=D.unload=D.prototype.unload;var M=window,N;(N=M.define)&&N.amd?N([],function(){return D}):"object"===typeof M.exports?M.module.exports=D:M.Mikado=D;}).call(this);
